query_name: test
query_sigs: inputs/adrian_sigs
sources: "inputs/metagenomes_source-20220219.csv"
#sources: "inputs/metagenomes_source-20200708.csv"
wort_sigs: inputs/sigs
#wort_sigs: /data/wort/wort-sra/sigs/
threshold: 0.01
ksize: 31
